[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[runner]
fastReruns = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#ef3348"
backgroundColor = "#000000"
secondaryBackgroundColor = "#111111"
textColor = "#F8FAFC"
font = "sans serif"
